version: '3.8'

services:
  weather-mysql:
    image: mysql:8
    container_name: weather-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: weather_db
      MYSQL_USER: weather_user
      MYSQL_PASSWORD: weather_pass
      TZ: Asia/Kolkata
    ports:
      - "3306:3306"
    volumes:
      - weather-db-data:/var/lib/mysql

  weather-app:
    build: .
    container_name: weather-app
    restart: always
    environment:
      OPENWEATHER_API_KEY: cb47f4137621769e89ecf675c3c76e92
      DEFAULT_CITY: Bangalore
      DB_USER: weather_user
      DB_PASSWORD: weather_pass
      DB_HOST: weather-mysql
      DB_PORT: 3306
      DB_NAME: weather_db
      TZ: Asia/Kolkata
    ports:
      - "8501:8501"
    depends_on:
      - weather-mysql

volumes:
  weather-db-data:
